$.global.FishTools = {
    executeTool: executeTool,
    readEase: _readEase,
    applyEase: _applyEase,
    readVelocity: _readVelocity,
    applyVelocity: _applyVelocity,
    applyElastic: _applyElastic,
    debugProps: _debugProps,
    controllerRead: _controllerRead,
    controllerSetValue: _controllerSetValue,
    controllerSetAxis: _controllerSetAxis,
    controllerSetBlendMode: _controllerSetBlendMode,
    controllerSetVector: _controllerSetVector,
    controllerSetPositionAxis: _controllerSetPositionAxis,
    controllerSetPositionXY: _controllerSetPositionXY,
    controllerSetPositionZ: _controllerSetPositionZ,
    controllerSetShapeRoundness: _controllerSetShapeRoundness,
    controllerSetShapeSize: _controllerSetShapeSize,
    controllerSetShapeSizeBoth: _controllerSetShapeSizeBoth,
    controllerCommit: _controllerCommit,
    controllerBeginUndo: _controllerBeginUndo,
    controllerEndUndo: _controllerEndUndo,
    transportPlayPause: _transportPlayPause,
    transportGetPlayState: _transportGetPlayState,
    transportPrevMarker: _transportPrevMarker,
    transportNextMarker: _transportNextMarker,
    PP_BROWSE_FOLDER: function () { return tools.PP_BROWSE_FOLDER(); },
    PP_GET_PROJECT_INFO: function () { return tools.PP_GET_PROJECT_INFO(); },
    PP_GET_VERSIONS: function () { return tools.PP_GET_VERSIONS(); },
    PP_CREATE_PRESET: function (name, loc, am, down, ver) { return tools.PP_CREATE_PRESET(name, loc, am, down, ver); },
    PP_LIST_MEDIA: function () { return tools.PP_LIST_MEDIA(); },
    PP_REPLACE_MEDIA: function (id, name) { return tools.PP_REPLACE_MEDIA(id, name); },
    PP_REVEAL_FOLDER: function (path) { return tools.PP_REVEAL_FOLDER(path); }
};
